name: main

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.event_name != 'schedule' || github.repository == 'JrMasterModelBuilder/multiups'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Test
        run: bash spec/test.sh

      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: ${{ vars.KA_COMMIT_MESSAGE }}
          committer_username: ${{ vars.KA_COMMIT_USER }}
          committer_email: ${{ secrets.KA_COMMIT_EMAIL }}
